### ISSUE TITLE
No user permissions available

### ISSUE THREAD

**Issue by brandonhowlett** [lupinelab/proxmox_wol#3]
I'm likely being dense, but maybe there's a step worth adding to the readme.

After adding the pam user and creating the respective role, I found that there are no available permissions for the proxmox_wol user. Alternatively, the root user has many.

Does the proxmox_wol user need to be added to another group after creation?

**Comment by jedrw** [comment]
You'll need to "Add" the permissions from the Permissions page as per the next step in the readme

**Comment by brandonhowlett** [comment]
Found it, Datacenter > Permissions.

Being newer to proxmox I was looking under Datacenter > Permissions > Users > Permissions, thinking  Datacenter > Permissions was just a drop-down label.

**Comment by jedrw** [comment]
Think I was caught out by the same thing once. Glad you've got it sorted.
